name: Deploy Jekyll and React to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Jekyll Build
      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # React Build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Ensure this matches your React project requirement

      - name: Install React dependencies
        run: npm install
        working-directory: ./ # Change this if your React project is inside a subdirectory

      - name: Build React App
        run: npm run build
        working-directory: ./ # Adjust if needed

      # Debugging step to check if build exists
      - name: Check React Build Directory
        run: ls -la ./build || echo "React build directory missing!"

      # Move React Build inside Jekyll _site
      - name: Merge React into Jekyll Site
        run: |
          mkdir -p ./_site/react
          mv ./build/* ./_site/react/
        if: success() # Only runs if the build was successful

      - name: Upload Combined Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
